import '@/styles/globals.css';

import type { Metadata } from 'next';
import { appConfig } from '@/configs/app';
import { novFont } from '@/lib/fonts';

export const metadata: Metadata = {
  title: appConfig.name,
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={novFont.className}>{children}</body>
    </html>
  );
}
